### ISSUE TITLE
Trying to implement custom music but get loud beeping noise

### ISSUE THREAD

**Issue by SonicFan8967** [SFGrenade/CustomBgm#2]
Whenever I try to input a wav file into the CustomBgm folder for certain music in the game (ex. Title, Dirtmouth 1), I get this loud beeping noise instead. Can someone please implement a better tutorial? I'm not an experienced modder and I just want to implement custom music into the game without trying to wrap my head around this. Is there a way to fix this issue? The version I'm using is 1.0.0.0. I tried using the newer version, but it somehow couldn't load for me.

**Comment by DwarfWoot** [comment]
Per SFG: the wav must be a 44.1 khz sample rate wav file.

**Comment by SonicFan8967** [comment]
Thanks. Managed to figure that problem out. Just had to edit the file in Audacity. Thanks again for your help!
