### ISSUE TITLE
Cannot replace the background music for Resting Grounds

### ISSUE THREAD

**Issue by SonicFan8967** [SFGrenade/CustomBgm#3]
For some reason, I cannot replace the BGM for the Resting Grounds. Even stranger, whenever I do enter the Resting Grounds, the name of the BGM does not appear in the ModLog - even after I exit the game it does not input the name in the ModLog. I'm not sure if it's a bug or something else, but is there a fix for this? The other custom BGMs work fine, and this is the only BGM I am unable to change into a custom BGM. I use the recent version of Hollow Knight, 1.5, and I noticed that the inability to replace the BGM for the Resting Grounds into a custom one is present in version 1.0.

**Comment by SFGrenade** [comment]
After checking it, it appears that the resting grounds only have a background music when you have the dream nail, otherwise it's just atmospheric sounds.

**Comment by SFGrenade** [comment]
And after you get the dream nail the sound files are `RESTING GROUNDS S51-14` and `S19 Optional Drone`

**Comment by SonicFan8967** [comment]
Nope. I did rename the custom BGM file into the exact name (RESTING GROUNDS S51-14) and made sure it was 44100Hz. It still plays the original Resting Grounds BGM - with the acquirement of the dream nail, of course. Am I doing something wrong, or is that the game and/or mod is not registering the custom replacement for the Resting Grounds BGM? I do have the dream nail and the BGM plays, but it's only the original song. I'm not so sure what to do, to be honest.

**Comment by SFGrenade** [comment]
Oh, error on my side, will be resolved today with an update.
